### ISSUE TITLE
Buildroot update for latest toolchain

### ISSUE THREAD

**Issue by ekromskoy** [foss-for-synopsys-dwc-arc-processors/buildroot#3]
Hello,

Just downloaded released here toolchain for ARC; it happened to be 6.2.1 GNU/GCC based one. Could not use this 2016.09 toolchain with buildroot downloaded from here as a top supported (available in menuconfig) toolchain version is 5.x. 

Do you have any plans to align released/supported versions?

Thank you,
Ed

**Comment by vlad-zkhr** [comment]
Hi Ed.
We are pleased to inform you that ARC is now supported in upstream Buildroot.
And it uses ARC toolchain 2016.09 by default.
You can get sources from buildroot git:
https://git.buildroot.net/buildroot

If you prefer to use released buildroot version you can take latest Buildroot v2016.11. It is configured with 2016.09-rc1 ARC toolchain. So you can either set up external toolchain 2016.09 or wait for upcoming Buildroot v2017.02.

--
Best regards,
Vlad

**Comment by ekromskoy** [comment]
Hi Vlad,

Thank you for a prompt response. I noticed that latest release of upstream buildroot has ARC support but I was not sure whether it's usable or not. My colleague insisted that this is a proper place for ARC buildroot. I glad to hear that ARC is now fully integrated in upstream Buildroot. 

Cheers,
Ed
